title:            Arnaud Porterie
disqus_shortname:
description:      Personal website and blog
reading_time:     false
logo:             images/logo_small.png
google_analytics: UA-78642707-1

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://icecrime.net

menu:
  - title: 'Home'
    url: '/'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Media'
    url: '/media'
  - title: 'About'
    url: '/about'

# Owner/author information
owner:
  name:           Arnaud Porterie
  site:           https://icecrime.net
  avatar:         images/avatar.jpg
  bio:            "Arnaud Porterie is currently Deputy CTO at Veepee, and was
                  previously a core maintainer of the Docker open-source project
                  and engineering leader for the Engine team inside Docker, Inc."
  email:          arnaud.porterie+web@gmail.com

  # Social networking links used in footer. Update and remove as you like.
  twitter: icecrime
  github: icecrime
  stackexchange: icecrime
  linkedin: aporterie
  flickr: icecrime

social:
  - title: "twitter"
    url: "https://twitter.com/icecrime"
  - title: "github"
    url: "https://github.com/icecrime"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/aporterie"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/451980/icecrime"
  - title: "flickr"
    url: "https://www.flickr.com/arnaudporterie"

collections:
  - media_timeline

# Background image to be tiled on all pages
background:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

#syntax_highlighter: coderay

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
